import '../../app/_shared/data/dto/get_countries_dto/get_countries_country_dto.dart';

class CountriesUtil {

  List<CountryDto> countries =[
    {
      'id': 3,
      'name': 'Afghanistan',
      'region': 'Asia',
      'code': 'AFN',
      'dial_code': '+93',
      'emoji': '🇦🇫',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg',
      'symbol': '?',
      'price_rate': '78.33'
    },
    {
      'id': 1,
      'name': 'Albania',
      'region': 'Europe',
      'code': 'ALL',
      'dial_code': '+355',
      'emoji': '🇦🇱',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg',
      'symbol': 'Lek',
      'price_rate': '104.73'
    },
    {
      'id': 4,
      'name': 'Argentina',
      'region': 'Americas',
      'code': 'ARS',
      'dial_code': '+54',
      'emoji': '🇦🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg',
      'symbol': r'$',
      'price_rate': '20.63'
    },
    {
      'id': 5,
      'name': 'Aruba',
      'region': 'Americas',
      'code': 'AWG',
      'dial_code': '+297',
      'emoji': '🇦🇼',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg',
      'symbol': '',
      'price_rate': '1.80'
    },
    {
      'id': 6,
      'name': 'Australia',
      'region': 'Oceania',
      'code': 'AUD',
      'dial_code': '+61',
      'emoji': '🇦🇺',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 7,
      'name': 'Azerbaijan',
      'region': 'Asia',
      'code': 'AZN',
      'dial_code': '+994',
      'emoji': '🇦🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg',
      'symbol': '???',
      'price_rate': '1.70'
    },
    {
      'id': 8,
      'name': 'Bahamas',
      'region': null,
      'code': 'BSD',
      'dial_code': '+1242',
      'emoji': null,
      'image': null,
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 9,
      'name': 'Barbados',
      'region': null,
      'code': 'BBD',
      'dial_code': '+1246',
      'emoji': null,
      'image': null,
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 10,
      'name': 'Belarus',
      'region': 'Europe',
      'code': 'BYR',
      'dial_code': '+375',
      'emoji': '🇧🇾',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg',
      'symbol': 'p.',
      'price_rate': '75.81'
    },
    {
      'id': 11,
      'name': 'Belgium',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+32',
      'emoji': '🇧🇪',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 12,
      'name': 'Beliz',
      'region': 'Americas',
      'code': 'BZD',
      'dial_code': '+501',
      'emoji': '🇧🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg',
      'symbol': r'BZ$',
      'price_rate': '1'
    },
    {
      'id': 13,
      'name': 'Bermuda',
      'region': null,
      'code': 'BMD',
      'dial_code': '+1441',
      'emoji': null,
      'image': null,
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 14,
      'name': 'Bolivia',
      'region': 'Americas',
      'code': 'BOB',
      'dial_code': '+591',
      'emoji': '🇧🇴',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg',
      'symbol': r'$b',
      'price_rate': '6.91'
    },
    {
      'id': 15,
      'name': 'Bosnia and Herzegovina',
      'region': 'Europe',
      'code': 'BAM',
      'dial_code': '+387',
      'emoji': '🇧🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg',
      'symbol': 'KM',
      'price_rate': '1.66'
    },
    {
      'id': 16,
      'name': 'Botswana',
      'region': 'Africa',
      'code': 'BWP',
      'dial_code': '+267',
      'emoji': '🇧🇼',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg',
      'symbol': 'P',
      'price_rate': '11.09'
    },
    {
      'id': 18,
      'name': 'Brazil',
      'region': 'Americas',
      'code': 'BRL',
      'dial_code': '+55',
      'emoji': '🇧🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg',
      'symbol': r'R$',
      'price_rate': '5.78'
    },
    {
      'id': 19,
      'name': 'Britain (United Kingdom)',
      'region': 'Europe',
      'code': 'GBP',
      'dial_code': '+44',
      'emoji': '🇬🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 20,
      'name': 'Brunei Darussalam',
      'region': 'Asia',
      'code': 'BND',
      'dial_code': '+673',
      'emoji': '🇧🇳',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 17,
      'name': 'Bulgaria',
      'region': 'Europe',
      'code': 'BGN',
      'dial_code': '+359',
      'emoji': '🇧🇬',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg',
      'symbol': '??',
      'price_rate': '1.67'
    },
    {
      'id': 21,
      'name': 'Cambodia',
      'region': 'Asia',
      'code': 'KHR',
      'dial_code': '+855',
      'emoji': '🇰🇭',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg',
      'symbol': '?',
      'price_rate': '4054.70'
    },
    {
      'id': 22,
      'name': 'Canada',
      'region': 'Americas',
      'code': 'CAD',
      'dial_code': '+1',
      'emoji': '🇨🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 23,
      'name': 'Cayman Islands',
      'region': null,
      'code': 'KYD',
      'dial_code': '+345',
      'emoji': null,
      'image': null,
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 24,
      'name': 'Chile',
      'region': 'Americas',
      'code': 'CLP',
      'dial_code': '+56',
      'emoji': '🇨🇱',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg',
      'symbol': r'$',
      'price_rate': '20.63'
    },
    {
      'id': 25,
      'name': 'China',
      'region': 'Asia',
      'code': 'CNY',
      'dial_code': '+86',
      'emoji': '🇨🇳',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg',
      'symbol': '',
      'price_rate': '6.57'
    },
    {
      'id': 26,
      'name': 'Colombia',
      'region': 'Americas',
      'code': 'COP',
      'dial_code': '+57',
      'emoji': '🇨🇴',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg',
      'symbol': r'$',
      'price_rate': '20.63'
    },
    {
      'id': 27,
      'name': 'Costa Rica',
      'region': 'Americas',
      'code': 'CRC',
      'dial_code': '+506',
      'emoji': '🇨🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg',
      'symbol': '?',
      'price_rate': '612.56'
    },
    {
      'id': 28,
      'name': 'Croatia',
      'region': 'Europe',
      'code': 'HRK',
      'dial_code': '+385',
      'emoji': '🇭🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg',
      'symbol': 'kn',
      'price_rate': '6.45'
    },
    {
      'id': 29,
      'name': 'Cuba',
      'region': 'Americas',
      'code': 'CUP',
      'dial_code': '+53',
      'emoji': '🇨🇺',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg',
      'symbol': '?',
      'price_rate': '20.63'
    },
    {
      'id': 30,
      'name': 'Cyprus',
      'region': 'Asia',
      'code': 'EUR',
      'dial_code': '+357',
      'emoji': '🇨🇾',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 31,
      'name': 'Czech Republic',
      'region': 'Europe',
      'code': 'CZK',
      'dial_code': '+420',
      'emoji': '🇨🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg',
      'symbol': 'K?',
      'price_rate': '22.23'
    },
    {
      'id': 32,
      'name': 'Denmark',
      'region': 'Europe',
      'code': 'DKK',
      'dial_code': '+45',
      'emoji': '🇩🇰',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg',
      'symbol': 'kr',
      'price_rate': '8.55'
    },
    {
      'id': 33,
      'name': 'Dominican Republic',
      'region': null,
      'code': 'DOP ',
      'dial_code': '+1849',
      'emoji': null,
      'image': null,
      'symbol': r'RD$',
      'price_rate': '20.63'
    },
    {
      'id': 35,
      'name': 'Egypt',
      'region': 'Africa',
      'code': 'EGP',
      'dial_code': '+20',
      'emoji': '🇪🇬',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 36,
      'name': 'El Salvador',
      'region': 'Americas',
      'code': 'SVC',
      'dial_code': '+503',
      'emoji': '🇸🇻',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg',
      'symbol': r'$',
      'price_rate': '612.56'
    },
    {
      'id': 37,
      'name': 'England (United Kingdom)',
      'region': 'Europe',
      'code': 'GBP',
      'dial_code': '+44',
      'emoji': '🇬🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 39,
      'name': 'Falkland Islands',
      'region': 'Americas',
      'code': 'FKP',
      'dial_code': '+500',
      'emoji': '🇫🇰',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 40,
      'name': 'Fiji',
      'region': 'Oceania',
      'code': 'FJD',
      'dial_code': '+679',
      'emoji': '🇫🇯',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 41,
      'name': 'France',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+33',
      'emoji': '🇫🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 135,
      'name': 'Gambian',
      'region': 'Africa',
      'code': 'GMD',
      'dial_code': '+220',
      'emoji': '🇬🇲',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg',
      'symbol': 'D',
      'price_rate': '51.10'
    },
    {
      'id': 42,
      'name': 'Ghana',
      'region': 'Africa',
      'code': 'GHS',
      'dial_code': '+233',
      'emoji': '🇬🇭',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg',
      'symbol': '',
      'price_rate': '5.78'
    },
    {
      'id': 43,
      'name': 'Gibraltar',
      'region': 'Europe',
      'code': 'GIP',
      'dial_code': '+350',
      'emoji': '🇬🇮',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 44,
      'name': 'Greece',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+30',
      'emoji': '🇬🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 45,
      'name': 'Guatemala',
      'region': 'Americas',
      'code': 'GTQ',
      'dial_code': '+502',
      'emoji': '🇬🇹',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg',
      'symbol': 'Q',
      'price_rate': '7.72'
    },
    {
      'id': 46,
      'name': 'Guernsey',
      'region': 'Europe',
      'code': 'GGP',
      'dial_code': '+44',
      'emoji': '🇬🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 47,
      'name': 'Guyana',
      'region': 'Americas',
      'code': 'GYD',
      'dial_code': '+595',
      'emoji': '🇵🇾',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 48,
      'name': 'Holland (Netherlands)',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+31',
      'emoji': '🇳🇱',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 49,
      'name': 'Honduras',
      'region': 'Americas',
      'code': 'HNL',
      'dial_code': '+504',
      'emoji': '🇭🇳',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg',
      'symbol': 'L',
      'price_rate': '24.02'
    },
    {
      'id': 50,
      'name': 'Hong Kong',
      'region': 'Asia',
      'code': 'HKD',
      'dial_code': '+852',
      'emoji': '🇭🇰',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 51,
      'name': 'Hungary',
      'region': 'Europe',
      'code': 'HUF',
      'dial_code': '+36',
      'emoji': '🇭🇺',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg',
      'symbol': 'Ft',
      'price_rate': '309.12'
    },
    {
      'id': 52,
      'name': 'Iceland',
      'region': 'Europe',
      'code': 'ISK',
      'dial_code': '+354',
      'emoji': '🇮🇸',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg',
      'symbol': 'kr',
      'price_rate': '127.70'
    },
    {
      'id': 132,
      'name': 'India',
      'region': 'Asia',
      'code': 'INR',
      'dial_code': '+91',
      'emoji': '🇮🇳',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg',
      'symbol': '₹',
      'price_rate': '72.79750'
    },
    {
      'id': 54,
      'name': 'Indonesia',
      'region': 'Asia',
      'code': 'IDR',
      'dial_code': '+62',
      'emoji': '🇮🇩',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg',
      'symbol': 'Rp',
      'price_rate': '14518.25'
    },
    {
      'id': 55,
      'name': 'Iran',
      'region': 'Asia',
      'code': 'IRR',
      'dial_code': '+98',
      'emoji': '🇮🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg',
      'symbol': '?',
      'price_rate': '42105.00'
    },
    {
      'id': 56,
      'name': 'Ireland',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+353',
      'emoji': '🇮🇪',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 57,
      'name': 'Isle of Man',
      'region': 'Europe',
      'code': 'IMP',
      'dial_code': '+44',
      'emoji': '🇬🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 58,
      'name': 'Israel',
      'region': 'Asia',
      'code': 'ILS',
      'dial_code': '+972',
      'emoji': '🇮🇱',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg',
      'symbol': '?',
      'price_rate': '3.32'
    },
    {
      'id': 59,
      'name': 'Italy',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+39',
      'emoji': '🇮🇹',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 60,
      'name': 'Jamaica',
      'region': null,
      'code': 'JMD',
      'dial_code': '+1876',
      'emoji': null,
      'image': null,
      'symbol': r'J$',
      'price_rate': '1'
    },
    {
      'id': 61,
      'name': 'Japan',
      'region': 'Asia',
      'code': 'JPY',
      'dial_code': '+81',
      'emoji': '🇯🇵',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg',
      'symbol': '',
      'price_rate': '110.24'
    },
    {
      'id': 62,
      'name': 'Jersey',
      'region': 'Europe',
      'code': 'JEP',
      'dial_code': '+44',
      'emoji': '🇬🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 63,
      'name': 'Kazakhstan',
      'region': null,
      'code': 'KZT',
      'dial_code': '+77',
      'emoji': null,
      'image': null,
      'symbol': '??',
      'price_rate': '424.47'
    },
    {
      'id': 134,
      'name': 'Kenya',
      'region': 'Africa',
      'code': 'KES',
      'dial_code': '+254',
      'emoji': '🇰🇪',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg',
      'symbol': 'KSh',
      'price_rate': '108.43'
    },
    {
      'id': 64,
      'name': 'Korea (North)',
      'region': 'Asia',
      'code': 'KPW',
      'dial_code': '+850',
      'emoji': '🇰🇵',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg',
      'symbol': '?',
      'price_rate': '1134.06'
    },
    {
      'id': 65,
      'name': 'Korea (South)',
      'region': 'Asia',
      'code': 'KRW',
      'dial_code': '+82',
      'emoji': '🇰🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg',
      'symbol': '?',
      'price_rate': '1134.06'
    },
    {
      'id': 66,
      'name': 'Kyrgyzstan',
      'region': 'Asia',
      'code': 'KGS',
      'dial_code': '+996',
      'emoji': '🇰🇬',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg',
      'symbol': '??',
      'price_rate': '84.78'
    },
    {
      'id': 67,
      'name': 'Laos',
      'region': 'Asia',
      'code': 'LAK',
      'dial_code': '+856',
      'emoji': '🇱🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg',
      'symbol': '?',
      'price_rate': '9395.36'
    },
    {
      'id': 68,
      'name': 'Latvia',
      'region': 'Europe',
      'code': 'LVL',
      'dial_code': '+371',
      'emoji': '🇱🇻',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg',
      'symbol': 'Ls',
      'price_rate': '3.37987'
    },
    {
      'id': 69,
      'name': 'Lebanon',
      'region': 'Asia',
      'code': 'LBP',
      'dial_code': '+961',
      'emoji': '🇱🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 70,
      'name': 'Liberia',
      'region': 'Africa',
      'code': 'LRD',
      'dial_code': '+231',
      'emoji': '🇱🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 71,
      'name': 'Liechtenstein',
      'region': 'Europe',
      'code': 'CHF',
      'dial_code': '+423',
      'emoji': '🇱🇮',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg',
      'symbol': 'CHF',
      'price_rate': '0.94'
    },
    {
      'id': 72,
      'name': 'Lithuania',
      'region': 'Europe',
      'code': 'LTL',
      'dial_code': '+370',
      'emoji': '🇱🇹',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg',
      'symbol': 'Lt',
      'price_rate': '2.93'
    },
    {
      'id': 73,
      'name': 'Luxembourg',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+352',
      'emoji': '🇱🇺',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 74,
      'name': 'Macedonia',
      'region': 'Europe',
      'code': 'MKD',
      'dial_code': '+389',
      'emoji': '🇲🇰',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg',
      'symbol': '???',
      'price_rate': '52.43'
    },
    {
      'id': 75,
      'name': 'Malaysia',
      'region': 'Asia',
      'code': 'MYR',
      'dial_code': '+60',
      'emoji': '🇲🇾',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg',
      'symbol': 'RM',
      'price_rate': '4.15'
    },
    {
      'id': 76,
      'name': 'Malta',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+356',
      'emoji': '🇲🇹',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 77,
      'name': 'Mauritius',
      'region': 'Africa',
      'code': 'MUR',
      'dial_code': '+230',
      'emoji': '🇲🇺',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg',
      'symbol': '?',
      'price_rate': '72.79750'
    },
    {
      'id': 78,
      'name': 'Mexico',
      'region': 'Americas',
      'code': 'MXN',
      'dial_code': '+52',
      'emoji': '🇲🇽',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg',
      'symbol': r'$',
      'price_rate': '20.63'
    },
    {
      'id': 79,
      'name': 'Mongolia',
      'region': 'Asia',
      'code': 'MNT',
      'dial_code': '+976',
      'emoji': '🇲🇳',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg',
      'symbol': '?',
      'price_rate': '2850.6'
    },
    {
      'id': 80,
      'name': 'Mozambique',
      'region': 'Africa',
      'code': 'MZN',
      'dial_code': '+258',
      'emoji': '🇲🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg',
      'symbol': 'MT',
      'price_rate': '69.96'
    },
    {
      'id': 81,
      'name': 'Namibia',
      'region': 'Africa',
      'code': 'NAD',
      'dial_code': '+264',
      'emoji': '🇳🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 82,
      'name': 'Nepal',
      'region': 'Asia',
      'code': 'NPR',
      'dial_code': '+977',
      'emoji': '🇳🇵',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg',
      'symbol': '?',
      'price_rate': '72.79750'
    },
    {
      'id': 84,
      'name': 'Netherlands',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+31',
      'emoji': '🇳🇱',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 83,
      'name': 'Netherlands Antilles',
      'region': 'Americas',
      'code': 'ANG',
      'dial_code': '+599',
      'emoji': '🇧🇶',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BQ.svg',
      'symbol': '',
      'price_rate': '1.80'
    },
    {
      'id': 85,
      'name': 'New Zealand',
      'region': 'Oceania',
      'code': 'NZD',
      'dial_code': '+64',
      'emoji': '🇳🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 86,
      'name': 'Nicaragua',
      'region': 'Americas',
      'code': 'NIO',
      'dial_code': '+505',
      'emoji': '🇳🇮',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg',
      'symbol': r'C$',
      'price_rate': '34.90'
    },
    {
      'id': 87,
      'name': 'Nigeria',
      'region': 'Africa',
      'code': 'NGN',
      'dial_code': '+234',
      'emoji': '🇳🇬',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg',
      'symbol': '₦',
      'price_rate': '380'
    },
    {
      'id': 88,
      'name': 'North Korea',
      'region': 'Asia',
      'code': 'KPW',
      'dial_code': '+850',
      'emoji': '🇰🇵',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg',
      'symbol': '?',
      'price_rate': '1134.06'
    },
    {
      'id': 89,
      'name': 'Norway',
      'region': 'Europe',
      'code': 'NOK',
      'dial_code': '+47',
      'emoji': '🇳🇴',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg',
      'symbol': 'kr',
      'price_rate': '8.56'
    },
    {
      'id': 90,
      'name': 'Oman',
      'region': 'Asia',
      'code': 'OMR',
      'dial_code': '+968',
      'emoji': '🇴🇲',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg',
      'symbol': '?',
      'price_rate': '42105.00'
    },
    {
      'id': 91,
      'name': 'Pakistan',
      'region': 'Asia',
      'code': 'PKR',
      'dial_code': '+92',
      'emoji': '🇵🇰',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg',
      'symbol': '?',
      'price_rate': '72.79750'
    },
    {
      'id': 92,
      'name': 'Panama',
      'region': 'Americas',
      'code': 'PAB',
      'dial_code': '+507',
      'emoji': '🇵🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg',
      'symbol': 'B/.',
      'price_rate': '1'
    },
    {
      'id': 93,
      'name': 'Paraguay',
      'region': 'Americas',
      'code': 'PYG',
      'dial_code': '+595',
      'emoji': '🇵🇾',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg',
      'symbol': 'Gs',
      'price_rate': '6445.24'
    },
    {
      'id': 94,
      'name': 'Peru',
      'region': 'Americas',
      'code': 'PEN',
      'dial_code': '+51',
      'emoji': '🇵🇪',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg',
      'symbol': 'S/.',
      'price_rate': '3.73'
    },
    {
      'id': 95,
      'name': 'Philippines',
      'region': 'Asia',
      'code': 'PHP',
      'dial_code': '+63',
      'emoji': '🇵🇭',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg',
      'symbol': 'Php',
      'price_rate': '20.63'
    },
    {
      'id': 96,
      'name': 'Poland',
      'region': 'Europe',
      'code': 'PLN',
      'dial_code': '+48',
      'emoji': '🇵🇱',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg',
      'symbol': 'z?',
      'price_rate': '3.96'
    },
    {
      'id': 97,
      'name': 'Qatar',
      'region': 'Asia',
      'code': 'QAR',
      'dial_code': '+974',
      'emoji': '🇶🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg',
      'symbol': '?',
      'price_rate': '42105.00'
    },
    {
      'id': 98,
      'name': 'Romania',
      'region': 'Europe',
      'code': 'RON',
      'dial_code': '+40',
      'emoji': '🇷🇴',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg',
      'symbol': 'lei',
      'price_rate': '4.18'
    },
    {
      'id': 99,
      'name': 'Russia',
      'region': 'Asia',
      'code': 'RUB',
      'dial_code': '+7',
      'emoji': '🇰🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg',
      'symbol': '???',
      'price_rate': '75.81'
    },
    {
      'id': 138,
      'name': 'Rwanda',
      'region': 'Africa',
      'code': 'RWF',
      'dial_code': '+250',
      'emoji': '🇷🇼',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg',
      'symbol': 'FRw',
      'price_rate': '1000.52'
    },
    {
      'id': 100,
      'name': 'Saint Helena',
      'region': 'Africa',
      'code': 'SHP',
      'dial_code': '+290',
      'emoji': '🇸🇭',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 101,
      'name': 'Saudi Arabia',
      'region': 'Asia',
      'code': 'SAR',
      'dial_code': '+966',
      'emoji': '🇸🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg',
      'symbol': '?',
      'price_rate': '3.75'
    },
    {
      'id': 102,
      'name': 'Serbia',
      'region': 'Europe',
      'code': 'RSD',
      'dial_code': '+381',
      'emoji': '🇷🇸',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg',
      'symbol': '???',
      'price_rate': '0.30'
    },
    {
      'id': 103,
      'name': 'Seychelles',
      'region': 'Africa',
      'code': 'SCR',
      'dial_code': '+248',
      'emoji': '🇸🇨',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg',
      'symbol': '?',
      'price_rate': '72.79750'
    },
    {
      'id': 137,
      'name': 'Sierra Leone',
      'region': 'Africa',
      'code': 'SLL',
      'dial_code': '+232',
      'emoji': '🇸🇱',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg',
      'symbol': 'Le',
      'price_rate': '10200.00'
    },
    {
      'id': 104,
      'name': 'Singapore',
      'region': 'Asia',
      'code': 'SGD',
      'dial_code': '+65',
      'emoji': '🇸🇬',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 105,
      'name': 'Slovenia',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+386',
      'emoji': '🇸🇮',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 106,
      'name': 'Solomon Islands',
      'region': 'Oceania',
      'code': 'SBD',
      'dial_code': '+677',
      'emoji': '🇸🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 107,
      'name': 'Somalia',
      'region': 'Africa',
      'code': 'SOS',
      'dial_code': '+252',
      'emoji': '🇸🇴',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg',
      'symbol': 'S',
      'price_rate': '2318.50'
    },
    {
      'id': 108,
      'name': 'South Africa',
      'region': 'Africa',
      'code': 'ZAR',
      'dial_code': '+27',
      'emoji': '🇿🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg',
      'symbol': 'R',
      'price_rate': '14.93'
    },
    {
      'id': 109,
      'name': 'South Korea',
      'region': 'Asia',
      'code': 'KRW',
      'dial_code': '+82',
      'emoji': '🇰🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg',
      'symbol': '?',
      'price_rate': '1134.06'
    },
    {
      'id': 110,
      'name': 'Spain',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+34',
      'emoji': '🇪🇸',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 111,
      'name': 'Sri Lanka',
      'region': 'Asia',
      'code': 'LKR',
      'dial_code': '+94',
      'emoji': '🇱🇰',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg',
      'symbol': '?',
      'price_rate': '72.79750'
    },
    {
      'id': 114,
      'name': 'Suriname',
      'region': 'Americas',
      'code': 'SRD',
      'dial_code': '+597',
      'emoji': '🇸🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 112,
      'name': 'Sweden',
      'region': 'Europe',
      'code': 'SEK',
      'dial_code': '+46',
      'emoji': '🇸🇪',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg',
      'symbol': 'kr',
      'price_rate': '8.72'
    },
    {
      'id': 113,
      'name': 'Switzerland',
      'region': 'Europe',
      'code': 'CHF',
      'dial_code': '+41',
      'emoji': '🇨🇭',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg',
      'symbol': 'CHF',
      'price_rate': '0.94'
    },
    {
      'id': 115,
      'name': 'Syria',
      'region': 'Asia',
      'code': 'SYP',
      'dial_code': '+963',
      'emoji': '🇸🇾',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 116,
      'name': 'Taiwan',
      'region': 'Asia',
      'code': 'TWD',
      'dial_code': '+886',
      'emoji': '🇹🇼',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg',
      'symbol': r'NT$',
      'price_rate': '28.50'
    },
    {
      'id': 136,
      'name': 'Tanzania',
      'region': 'Africa',
      'code': 'TZS',
      'dial_code': '+255',
      'emoji': '🇹🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg',
      'symbol': 'TSh',
      'price_rate': '3612.03'
    },
    {
      'id': 8800,
      'name': 'Test',
      'region': 'Test',
      'code': 'Test',
      'dial_code': '',
      'emoji': '',
      'image': null,
      'symbol': '',
      'price_rate': ''
    },
    {
      'id': 117,
      'name': 'Thailand',
      'region': 'Asia',
      'code': 'THB',
      'dial_code': '+66',
      'emoji': '🇹🇭',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg',
      'symbol': '?',
      'price_rate': '31.25'
    },
    {
      'id': 118,
      'name': 'Trinidad and Tobago',
      'region': null,
      'code': 'TTD',
      'dial_code': '+1868',
      'emoji': null,
      'image': null,
      'symbol': r'TT$',
      'price_rate': '1'
    },
    {
      'id': 119,
      'name': 'Turkey',
      'region': 'Asia',
      'code': 'TRY',
      'dial_code': '+90',
      'emoji': '🇹🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg',
      'symbol': 'TL',
      'price_rate': '8.32'
    },
    {
      'id': 120,
      'name': 'Turkey',
      'region': 'Asia',
      'code': 'TRL',
      'dial_code': '+90',
      'emoji': '🇹🇷',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg',
      'symbol': '',
      'price_rate': '8.32'
    },
    {
      'id': 121,
      'name': 'Tuvalu',
      'region': 'Oceania',
      'code': 'TVD',
      'dial_code': '+688',
      'emoji': '🇹🇻',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 139,
      'name': 'Uganda',
      'region': 'Africa',
      'code': 'UG',
      'dial_code': '+256',
      'emoji': '🇺🇬',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg',
      'symbol': 'USh',
      'price_rate': '3612.03'
    },
    {
      'id': 122,
      'name': 'Ukraine',
      'region': 'Europe',
      'code': 'UAH',
      'dial_code': '+380',
      'emoji': '🇺🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg',
      'symbol': '?',
      'price_rate': '27.99'
    },
    {
      'id': 123,
      'name': 'United Kingdom',
      'region': 'Europe',
      'code': 'GBP',
      'dial_code': '+44',
      'emoji': '🇬🇧',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
      'symbol': '',
      'price_rate': '0.73'
    },
    {
      'id': 124,
      'name': 'United States of America',
      'region': 'Americas',
      'code': 'USD',
      'dial_code': '+1',
      'emoji': '🇨🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg',
      'symbol': r'$',
      'price_rate': '1'
    },
    {
      'id': 125,
      'name': 'Uruguay',
      'region': 'Americas',
      'code': 'UYU',
      'dial_code': '+598',
      'emoji': '🇺🇾',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg',
      'symbol': r'$U',
      'price_rate': '20.63'
    },
    {
      'id': 126,
      'name': 'Uzbekistan',
      'region': 'Asia',
      'code': 'UZS',
      'dial_code': '+998',
      'emoji': '🇺🇿',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg',
      'symbol': '??',
      'price_rate': '10486.90'
    },
    {
      'id': 127,
      'name': 'Vatican City',
      'region': 'Europe',
      'code': 'EUR',
      'dial_code': '+379',
      'emoji': '🇻🇦',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg',
      'symbol': '',
      'price_rate': '0.85'
    },
    {
      'id': 128,
      'name': 'Venezuela',
      'region': 'Americas',
      'code': 'VEF',
      'dial_code': '+58',
      'emoji': '🇻🇪',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg',
      'symbol': 'Bs',
      'price_rate': '185,715,000,000'
    },
    {
      'id': 129,
      'name': 'Vietnam',
      'region': 'Asia',
      'code': 'VND',
      'dial_code': '+84',
      'emoji': '🇻🇳',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg',
      'symbol': '?',
      'price_rate': '23075.00'
    },
    {
      'id': 130,
      'name': 'Yemen',
      'region': 'Asia',
      'code': 'YER',
      'dial_code': '+967',
      'emoji': '🇾🇪',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg',
      'symbol': '?',
      'price_rate': '42105.00'
    },
    {
      'id': 131,
      'name': 'Zimbabwe',
      'region': 'Africa',
      'code': 'ZWD',
      'dial_code': '+263',
      'emoji': '🇿🇼',
      'image': 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg',
      'symbol': r'Z$',
      'price_rate': '361.9'
    }
  ].map(CountryDto.fromJson).toList();
}
