// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8uuNcrW1SD7EhmH-nUnMQBl_GHD9JmJU',
    appId: '1:925393777420:web:e0bbbefdd04d2eb1384f29',
    messagingSenderId: '925393777420',
    projectId: 'teesasv2',
    authDomain: 'teesasv2.firebaseapp.com',
    storageBucket: 'teesasv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlDxvyUQ0h4JmQEaOpvRs8M6cwpwwTOs',
    appId: '1:718122574249:android:5771273d8f2660b07c64b8',
    messagingSenderId: '718122574249',
    projectId: 'teesas-8a056',
    databaseURL: 'https://teesas-8a056.firebaseio.com',
    storageBucket: 'teesas-8a056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqljHfzCIzHSHNUVXNQD67ro9gpbphERk',
    appId: '1:718122574249:ios:c13be528286b0c9c7c64b8',
    messagingSenderId: '718122574249',
    projectId: 'teesas-8a056',
    databaseURL: 'https://teesas-8a056.firebaseio.com',
    storageBucket: 'teesas-8a056.firebasestorage.app',
    androidClientId: '718122574249-575aq83sojem1keun5hnf2plqjt1i31q.apps.googleusercontent.com',
    iosClientId: '718122574249-1o82daqga3et05ccs5oiuq9sl320pqg5.apps.googleusercontent.com',
    iosBundleId: 'com.Teesas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8uuNcrW1SD7EhmH-nUnMQBl_GHD9JmJU',
    appId: '1:925393777420:web:8e1b7fbb56c594a8384f29',
    messagingSenderId: '925393777420',
    projectId: 'teesasv2',
    authDomain: 'teesasv2.firebaseapp.com',
    storageBucket: 'teesasv2.firebasestorage.app',
  );

}